### ISSUE TITLE
Twig comments not supported

### ISSUE THREAD

**Issue by dave-irvine** [twigjs/twig.js#379] opened 2016-05-31 21:53 UTC
As reported in #377, Twig comments of the following format:

`{# Like That #}`

don't seem to work.

**Comment by olets** [comment] 2016-06-28 01:58
Comments are working fine for me. I wonder if there's a chance @TheMaxoor had a comment inside a function or something

**Comment by TheMaxoor** [comment] 2016-06-28 07:21
That's weird, it seems to me that my comments were just in my HTML normally. I don't remember putting some of these in functions or anything special 😕

**Comment by olets** [comment] 2016-06-28 16:07
Huh! Do comments ever work in twig.js for you? Strange

**Comment by willrowe** [comment] 2022-07-05 15:01
Closing due to lack of simple example to reproduce. Please reopen if this is still and issue and provide a simple example.

**Closed by willrowe** 2022-07-05 15:01 UTC
