### ISSUE TITLE
Bug/Error: second argument to Function.prototype.apply must be an array

### ISSUE THREAD

**Issue by ghost** [twigjs/twig.js#506] opened 2017-11-07 07:24 UTC
When I do this I get an error:

```
{{ test({'test':'some data', 'test2':{'aaa':'bbb'}}) }}
```

But when I do this, I don't get an error:

```
{% set data = {'test':'some data', 'test2':{'aaa':'bbb'}} %}
{{ test(data) }}
```

Even though the data is the same. 

Also, this works as well:

```
{{ test({'test':'some data', 'test2':[{'aaa':'bbb'}]}) }}
```

It seems that calling a (custom) function, even one that is completely empty (doesn't do anything), it will throw an error when there is an object that is a value of another object. 

The error it throws is "second argument to Function.prototype.apply must be an array".

The code that throws the error is the parse function:

```
parse: function(token, stack, context) {

    var that = this,
        fn = token.fn,
        value;

    return parseParams(this, token.params, context)
    .then(function(params) {
        if (Twig.functions[fn]) {
            // Get the function from the built-in functions
            value = Twig.functions[fn].apply(that, params);

        } else if (typeof context[fn] == 'function') {
            // Get the function from the user/context defined functions
            value = context[fn].apply(context, params);

        } else {
            throw new Twig.Error(fn + ' function does not exist and is not defined in the context');
        }

        return value;
    })
    .then(function(result) {
        stack.push(result);
    });
}
```

On this line:

```
value = Twig.functions[fn].apply(that, params);
```

This is my custom function by the way:

```
Twig.extendFunction('test', function(data)
{
	return '';
});
```

As you can see, it doesn't do anything. 

I'm using the latest version of Twig.js (the one found with npm). I include the twig.min.js directly. I've only tested this in the browser. 

Can anyone confirm this bug?

**Comment by prachikeubik** [comment] 2020-04-16 12:19
i am also getting same error when I added new field in xml. I am using Odoo10. but not got solution for the same.

**Comment by willrowe** [comment] 2022-07-07 18:36
I believe this is due to the double end brace being interpreted as an end of the print statement. You can see in [this example](https://codepen.io/willrowe/pen/jOzqPWa) that the first template errors out and the second with a space between the end braces works.

Duplicate of #3, there is a workaround available there until this can be fixed.

**Closed by willrowe** 2022-07-07 18:36 UTC
