### ISSUE TITLE
cannot render table rows || very weird problem

### ISSUE THREAD

**Issue by minhaj-resgef** [twigjs/twig.js#292] opened 2016-01-05 18:13 UTC
```
             <table>
                <thead>
                    <tr>
                        <th>Item</th>
                    </tr>
                </thead>
                <tbody>
                {% for item in [1,2,3] %}
                    <tr>
                        <td>{{item}}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
```
this generates only one table row with empty data for me

but this renders fine(three rows with with the intended numbers)
```
             <table>
                <thead>
                    <tr>
                        <th>Item</th>
                    </tr>
                </thead>
                <tbody>
                {% for item in [1,2,3] %}
                    <tr>
                        <p>{{item}}</p>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
```
I am totally stuck in this weird issue!!!
Anyone can identify what is going wrong?
Thanks in advance ...

**Comment by plepe** [comment] 2016-01-05 20:58
I copied the template, but it renders fine. Could you try with this fiddle that I've set up: http://jsfiddle.net/nre6b2of/1/?

**Comment by plepe** [comment] 2016-02-03 06:14
Still not working? Or could you identify a bug on your side?

**Comment by dave-irvine** [comment] 2016-04-19 14:29
No update in 30 days, closing.

**Closed by dave-irvine** 2016-04-19 14:29 UTC
Labels: support request

**Comment by akuehnis** [comment] 2017-02-16 04:22
I had the same issue and could reproduce it. However, it was (at least for me) not a twig.js related problem, but a strange rendering thing.

On page load, I first loaded template from the server and appended it to the document body. (Why? because I wanted them all to be in the DOM to be able to use Twig synchroneously):
```
    var url='./templates/'+view+".html.twig";
    $.get(url, function(content) {
        var element = '<template id="template_'+view+'">'+
            content+'</template>';
        $("body").append(element);
    });

```

This works fine except when there is a table/tr/td combination. In this case, the template in the DOM looks different than the original:

```
<template id="template_test">

                {% for item in [1,2,3] %}
                    
                {% endfor %}
                <table>
                <thead>
                    <tr>
                        <th>Item</th>
                    </tr>
                </thead>
                <tbody><tr>
                        <td>{{item}}</td>
                    </tr></tbody>
            </table>
</template>
```

I have no explanation for this behavior. 

My solution is to load templates async from the server at the time I need them and not try to put them into the DOM.
