### ISSUE TITLE
undefined template var + 1 = NaN

### ISSUE THREAD

**Issue by r3wt** [twigjs/twig.js#384] opened 2016-06-06 17:04 UTC
in php version, the result = 1

repro(s):

`{{ k + 1 }}`
`{{ k.foo + 1 }}`

**Comment by olets** [comment] 2016-06-28 01:55
I might be misunderstanding, but I think this is the same as #365?

**Comment by willrowe** [comment] 2022-07-05 15:01
Duplicate of #365.

**Closed** 2022-07-05 15:02 UTC
