### ISSUE TITLE
Provide an ESM build

### ISSUE THREAD

**Issue by drzraf** [twigjs/twig.js#697] opened 2019-12-17 20:23 UTC
It would be appreciable to add an ESM output to the [webpack.config.js](./webpack.config.js) and reference it in [package.json](./package.json) `module` field.
That way, ESM-enabled bundlers like rollup could make use of it.

**Comment by willrowe** [comment] 2022-07-29 20:43
The plan is to convert the entire project to ES modules in a future version. Duplicate of #622.

**Closed by willrowe** 2022-07-29 20:43 UTC
