### ISSUE TITLE
Feature request: Asynchronous function callback

### ISSUE THREAD

**Issue by rolyataylor2** [twigjs/twig.js#357] opened 2016-05-06 18:23 UTC
So what I am needing and I have been unable to figure out with the twig source is to allow for:

```
Twig.extendFunction("DatabaseCall", function (arguments) {
    return 'Template Stuff';
});
```

The problem is that node wants to do everything via callbacks... So what would be neat is to extend twig using a function that upon completion it does not continue rendering but instead waits for a callback... So like this...

```
Twig.extendFunctionAsync("Import", function (callback, name, twigVars) {
    // Pull database things
    Callback(ReturnVariable);
});
```

The exact problem I am having is I want to allow template creators to render items from the database using that function but to pull from the database it needs to be Async because node cannot do network calls synchronously.

I will keep plugging away at this but you guys have more insight as to how your renderer works... 

Thanks for reading 👍

**Comment by dave-irvine** [comment] 2016-05-06 18:26
So I think what you're trying to do is probably similar to: https://github.com/twigjs/twig.js/issues/61, is that right?

**Comment by rolyataylor2** [comment] 2016-05-06 18:33
I did not see that one. That is what I am intending to do because of the nature of a mysql call in node js.

**Comment by dave-irvine** [comment] 2016-05-06 18:36
Its definitely a cool idea, but unfortunately I really can't prioritize it at the moment because its not something you can do in Twig PHP. I'm currently aiming to try and get more compatibility with Twig PHP as my priority.

**Comment by rolyataylor2** [comment] 2016-05-06 18:39
Makes sense. I am thinking of maybe rendering the template and using a randomized token as a placeholder for the variable then after the render is done going though and replacing the tokens with the returned variables. So kinda like a double render or a basic .replace('DBVAR','info') kind of thing.

**Comment by kachurun** [comment] 2017-12-06 10:43
Why it not work with {% for %} tag?

Simple example:
Function:

```
Twig.extendFunction('async_test', (id) => {
    return Promise.resolve(`Test: ${ id }`);
});
```


Template: 
```
<div id="single>
    {{ async_test(1000) }}
</div>

// ids is [2000, 20001, 20002]
<div id="each">
    {% for id in ids  %}
        <div data-index="{{ loop.index }}">
            {{ async_test(id) }}
        </div>
    {% endfor %}
</div>
```

returns 
```
<div id="single>
    Test: 1000
</div>

<div id="each">
    
</div>
```

where #each is empty. 

How i can fix it?

**Comment by willrowe** [comment] 2022-07-05 14:57
Duplicate of #61.

**Closed by willrowe** 2022-07-05 14:57 UTC
Labels: status - on hold
