### ISSUE TITLE
local var `url`always undefined when used in importFile

### ISSUE THREAD

**Issue by ThaNarie** [twigjs/twig.js#459] opened 2017-03-11 22:50 UTC
In `Twig.Template.prototype.importFile`, the `sub_template = Twig.Templates.loadRemote(url, {` function is called where `url` is not yet defined, so always undefined:
https://github.com/twigjs/twig.js/blob/751a8ba41b4275ee480d9c6de87d221e052a4b17/src/twig.core.js#L1313

A few lines above it seems to be done correctly:
https://github.com/twigjs/twig.js/blob/751a8ba41b4275ee480d9c6de87d221e052a4b17/src/twig.core.js#L1248-L1250

**Comment by willrowe** [comment] 2022-07-05 20:21
Closing due to lack of simple example to reproduce.

If this is still an issue, please reopen and provide a [TwigFiddle](https://twigfiddle.com/) example of it working in TwigPHP and the same example in twig.js using [this template](https://codepen.io/pen?template=LYQawea).

**Closed by willrowe** 2022-07-05 20:21 UTC
