### ISSUE TITLE
Arrow / Lambda functions

### ISSUE THREAD

**Issue by antoineveldhoven** [twigjs/twig.js#861] opened 2023-04-03 08:47 UTC
Currently twig.js does not support arrow or lambda functions like:

```
{% for item in items|sort((a, b) => a.begin_time <=> b.begin_time) %}
   ...
{% endfor %}
```

This would be nice to get this implemented; I would like to add this functionality myself.
Could one of the maintainers point me out into the right direction; would you like this implemented as a logic token type or as an expression type?

P.S. : spaceship operator is also not supported; out of scope; just to point out the example; perhaps I will create an issue and a fix for this as well.

**Comment by willrowe** [comment] 2023-04-03 14:38
This is related to #652. As I see it, there would be several steps:

1. Add support for arrow functions in limited contexts to match where TwigPHP allows them.
2. Allow arrow functions to be used in filters that already exist like `sort`.
3. Add `filter`, `map`, and `reduce` filters that rely on support for arrow functions.

@antoineveldhoven I'm going to close this so that discussion can be consolidated into #652. I think it would be fine to complete all three of the steps above in one PR.

Duplicate of #652

**Comment by willrowe** [comment] 2023-04-03 14:38
Duplicate of #652

**Closed by willrowe** 2023-04-03 14:38 UTC
