### ISSUE TITLE
Extend absolute path file 

### ISSUE THREAD

**Issue by ccamensuli** [twigjs/twig.js#456] opened 2017-02-27 17:32 UTC
I had a problem  with extend an absolute path file in node.js 

This may correct it :
[extend bug details](https://github.com/nodefony/docker-nodefony/issues/1)

**Comment by katugtug** [comment] 2017-03-28 16:50
This is an issue for me as well.

**Comment by willrowe** [comment] 2022-07-05 20:19
Closing due to lack of simple example to reproduce.

If this is still an issue, please reopen and provide a TwigFiddle example of it working in TwigPHP and the same example in twig.js using [this template](https://codepen.io/pen?template=LYQawea).

**Closed by willrowe** 2022-07-05 20:19 UTC
